version: '3.8'

volumes:
  redis-data:
    driver: local

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    depends_on:
      - app  
  redis:
    image: 'redis:7.2-rc2-alpine'
    ports:
      - "6379"    
    volumes:
      - redis-data:/data  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: "always"  